#pragma once
#define ZENOH_C "1.7.2"
#define ZENOH_C_MAJOR 1
#define ZENOH_C_MINOR 7
#define ZENOH_C_PATCH 2
#define ZENOH_C_TWEAK

#define TARGET_ARCH_X86_64
#define Z_FEATURE_TRANSPORT_TCP
#define Z_FEATURE_TRANSPORT_MULTILINK
#define Z_FEATURE_TRANSPORT_UDP
#define Z_FEATURE_TRANSPORT_QUIC
#define Z_FEATURE_AUTH_USRPWD
#define Z_FEATURE_AUTH_PUBKEY
#define Z_FEATURE_TRANSPORT_TLS
#define Z_FEATURE_UNSTABLE_API
#define Z_FEATURE_TRANSPORT_WS
#define Z_FEATURE_SHARED_MEMORY
#define Z_FEATURE_TRANSPORT_UNIXSOCK_STREAM
